name: kmp-advcrypto
on:
  push:

jobs:
  build:
    name: Build and Test (Linux/x64)
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
      - name: Build and Test
        run: ./gradlew :kmp-advcrypto:cleanLinuxX64Test :kmp-advcrypto:linuxX64Test